# TP introduction à pandas

### Installer et importer pandas

Via conda : "conda install pandas".

Nous pouvons désormais l'importer dans le notebook:

In [29]:
import pandas as pd

### Charger un fichier avec pandas.

- read_csv est la méthode la plus souvent utilisées.
    - paramètres header et sep pour parser des fichiers avec des lignes d'en têtes et des séparateurs custom
- des méthodes équivalentes pour lire des fichiers excels, json, database sqlite, ... Cf la documentation !

In [33]:
df = pd.read_csv('athlete_events.csv')


head() et describe permettent de rapidement obtenir des informations sur le fichier que l'on a chargé

In [34]:
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [35]:
df.describe()

,ID,Age,Height,Weight,Year
count,271116.000000,261642.000000,210945.000000,208241.000000,271116.000000
mean,68248.954396,25.556898,175.338970,70.702393,1978.378480
std,39022.286345,6.393561,10.518462,14.348020,29.877632
min,1.000000,10.000000,127.000000,25.000000,1896.000000
25%,34643.000000,21.000000,168.000000,60.000000,1960.000000
50%,68205.000000,24.000000,175.000000,70.000000,1988.000000
75%,102097.250000,28.000000,183.000000,79.000000,2002.000000
max,135571.000000,97.000000,226.000000,214.000000,2016.000000

###  3) Manipuler un dataframe
#### Manipuler les colonnes

In [36]:
df.columns

Index(['ID', 'Name', 'Sex', 'Age', 'Height', 'Weight', 'Team', 'NOC', 'Games',
       'Year', 'Season', 'City', 'Sport', 'Event', 'Medal'],
      dtype='object')

In [37]:
df['ID']

0              1
1              2
2              3
3              4
4              5
           ...
271111    135569
271112    135570
271113    135570
271114    135571
271115    135571
Name: ID, Length: 271116, dtype: int64

- quel type de donnée est dans chaque colonne ?

In [38]:
df["ID"].dtypes

dtype('int64')

- on peut convertir d'un type de donnée à un autre via la méthode astype. Exemple : convertir en chaine de caractère.

In [39]:
df["ID"] = df["ID"].astype(float)
df["ID"].dtype

dtype('float64')

- unique() et nunique() permettent d'afficher toutes les valeurs uniques d'une colonne ou les compter

In [40]:
unique = df.Team.unique()
unique.tolist()

['China',
 'Denmark',
 'Denmark/Sweden',
 'Netherlands',
 'United States',
 'Finland',
 'Norway',
 'Romania',
 'Estonia',
 'France',
 'Taifun',
 'Morocco',
 'Spain',
 'Egypt',
 'Iran',
 'Bulgaria',
 'Italy',
 'Chad',
 'Azerbaijan',
 'Sudan',
 'Russia',
 'Argentina',
 'Cuba',
 'Belarus',
 'Greece',
 'Cameroon',
 'Turkey',
 'Chile',
 'Mexico',
 'Soviet Union',
 'Nicaragua',
 'Hungary',
 'Nigeria',
 'Algeria',
 'Kuwait',
 'Bahrain',
 'Pakistan',
 'Iraq',
 'United Arab Republic',
 'Lebanon',
 'Qatar',
 'Malaysia',
 'Germany',
 'Thessalonki-1',
 'Canada',
 'Ireland',
 'Australia',
 'South Africa',
 'Eritrea',
 'Tanzania',
 'Jordan',
 'Tunisia',
 'Libya',
 'Belgium',
 'Djibouti',
 'Palestine',
 'Comoros',
 'Kazakhstan',
 'Brunei',
 'India',
 'Saudi Arabia',
 'Syria',
 'Maldives',
 'Ethiopia',
 'United Arab Emirates',
 'North Yemen',
 'Indonesia',
 'Philippines',
 'Singapore',
 'Uzbekistan',
 'Kyrgyzstan',
 'Tajikistan',
 'Unified Team',
 'Japan',
 'Japan-1',
 'Congo (Brazzaville)',
 'Switzerland',
 'Brazil',
 'West Germany',
 'East Germany',
 'Monaco',
 'Fornebo',
 'Israel',
 'Vesper Boat Club',
 'Uruguay',
 'Sweden',
 'United States Virgin Islands',
 'Sri Lanka',
 'Armenia',
 "Cote d'Ivoire",
 'Kenya',
 'Benin',
 'France-1',
 'Ukraine',
 'Great Britain',
 'Ghana',
 'Somalia',
 'Latvia',
 'Niger',
 'Mali',
 'Afghanistan',
 'Poland',
 'Costa Rica',
 'Panama',
 'Georgia',
 'Slovenia',
 'Croatia',
 'Russia-2',
 'Russia-1',
 'Guyana',
 'New Zealand',
 'Portugal',
 'Paraguay',
 'Angola',
 'Venezuela',
 'Colombia',
 'Bangladesh',
 'Peru',
 'El Salvador',
 'Puerto Rico',
 'France-2',
 'Uganda',
 'Switzerland-2',
 'Switzerland-1',
 'Honduras',
 'Ecuador',
 'Turkmenistan',
 'Mauritius',
 'Seychelles',
 'Czechoslovakia',
 'Great Britain-1',
 'Luxembourg',
 'Mauritania',
 'Czech Republic',
 'Saint Kitts and Nevis',
 'New York Athletic Club #2-4',
 'Trinidad and Tobago',
 'Dominican Republic',
 'Saint Vincent and the Grenadines',
 'Mystery',
 'Jamaica',
 'Liberia',
 'Suriname',
 'Nigeria-2',
 'Nepal',
 'Mongolia',
 'Germany-2',
 'Austria',
 'Clementine V',
 'Bylina-2',
 'Palau',
 'Lithuania',
 'Togo',
 'Namibia',
 'Netherlands Antilles',
 'Iceland',
 'American Samoa',
 'Samoa',
 'Rwanda',
 'Dominica',
 'Great Britain-2',
 'Haiti',
 'Stella-2',
 'Malta',
 'United States-1',
 'United States-2',
 'Argentina-2',
 'Large boat, Central Naval Prep School "Poros"-1',
 'Cyprus',
 'Guinea',
 'Xolotl',
 'Belize',
 'Matrero II',
 'Blue Red',
 'Gteborgs Roddklubb-1',
 'Indonesia-1',
 'Germany-1',
 'South Yemen',
 'South Korea',
 'Lucky Girl-1',
 'Mutafo',
 'Sweden-2',
 'Sweden-1',
 'Thailand',
 'Italy-2',
 'Yeoman VII',
 'Yeoman XII',
 'Bermuda',
 'Australasia',
 'Union des Socits Franais de Sports Athletiques',
 'Serbia and Montenegro',
 'Sierra Leone',
 'Bissbi',
 'Papua New Guinea',
 'Greece-3',
 'Yemen',
 'Individual Olympic Athletes',
 'Oman',
 'Fiji',
 'Vanuatu',
 'France-3',
 'Martha-27',
 'Martha-1',
 'Moldova',
 'Canada-2',
 'Canada-1',
 'Yugoslavia',
 'Bahamas',
 'Guatemala',
 'Burevestnik',
 'Druzhba',
 'Soviet Union-2',
 'Soviet Union-1',
 'Olen',
 'Serbia',
 'British Virgin Islands',
 'Mozambique',
 'Heatherbell',
 'Central African Republic',
 'Madagascar',
 'Malaya',
 'Socit Nautique de Bayonne',
 'Bosnia and Herzegovina',
 'Guam',
 'Brazil-1',
 'Cayman Islands',
 'Cupidon Viking',
 'Damoiselle',
 'Slovakia',
 'USFSA',
 'The Cloud',
 'Galerna',
 'Heira II',
 'Nykjbings paa Falster',
 'Barbados',
 'Ireland-2',
 'Spain-2',
 'Guinea Bissau',
 'Mohawk Indians-2',
 'Tornado',
 'Elsie',
 'Roma',
 'Tajamar',
 'Spain-1',
 'Lemzos Thorichton "Spetsai"-4',
 'Norway-2',
 'Norway-1',
 'Italy-1',
 'Puerto Rico-2',
 'Mound City Rowing Club-2',
 'Timor Leste',
 'Amolgavar',
 'Congo (Kinshasa)',
 'Gabon',
 'Ali-Baba II',
 'May Be VII',
 'East Germany-1',
 'San Marino',
 'Favorite Hammonia-3',
 'Laos',
 'Botswana',
 'Refugee Olympic Athletes',
 'Frankfurt Club',
 'Lett',
 'GyoshuII',
 'North Korea',
 'South Korea-2',
 'Brazil-2',
 'Solomon Islands',
 'Dolfijn',
 'Senegal',
 'Cape Verde',
 'Tip',
 'Yugoslavia-1',
 'rn-2',
 'Crete',
 'Breslau',
 'Germany-3',
 'Romania-2',
 'Club Nautique de Dieppe-5',
 'Norna',
 'Fram',
 'Magda IX',
 'Soviet Union-3',
 'Equatorial Guinea',
 'Bolivia',
 'Saar',
 'Andorra',
 'Japan-2',
 'Austria-1',
 'Austria-2',
 'Antigua and Barbuda',
 'EA II',
 'Canada-3',
 'Czechoslovakia-3',
 'Linglom',
 'Denmark-2',
 'Mosk II',
 'Latvia-2',
 'Elisabeth X',
 'Sweden-3',
 'Ludwigshafener Ruderverein',
 'Australia-2',
 'Latvia-1',
 'Guyoni',
 'Greece-1',
 'Greece-2',
 'West Germany-2',
 'La Salle Turnverein, Chicago',
 'Gallant',
 'Zimbabwe',
 'Grenada',
 'Hera-1',
 'Swedish Star',
 'Bulgaria-1',
 'Nautikos Omilos-3',
 'Wolseley-Siddeley-1',
 'Hong Kong',
 'Ciocca II',
 'Mirtala',
 'Saint Lucia',
 'Carabinier-5',
 'Pettit-Poucet-6',
 'Carabinier-15',
 'Federated States of Micronesia',
 'Myanmar',
 'Hirondelle',
 'Kerstin-1',
 'Evita VI',
 'Ukraine-2',
 'Russia-3',
 'Malawi',
 'Belarus-1',
 'United States-3',
 'Bronia',
 'Zambia',
 'Denmark-1',
 'Bluebottle',
 'West Germany-1',
 'Rhodesia',
 'East Germany-2',
 'Snap',
 'Chinese Taipei-1',
 'Sao Tome and Principe',
 'Toronto Argonauts',
 'England-1',
 'Hungaria Evezos Egylet',
 'Poland-1',
 'Macedonia',
 'Bohemia',
 'Argonaut Rowing Club',
 'Life boat naval ship "Spetsai"-1',
 'Australia-1',
 'Tonga',
 'Nigeria-1',
 'Fortuna',
 'Starlight III',
 'Liechtenstein',
 'Pan',
 'Montenegro',
 'Leander Club-2',
 'Lemzos Thorichton "Psara"-3',
 'London City Police-1',
 'Great Britain-3',
 'Sabre',
 'Firebird II',
 'Berliner Ruderverein von 1876-2',
 "Christian Brothers' College-1",
 'Czechoslovakia-1',
 'Czechoslovakia-2',
 'Passaic Turnverein, Passaic',
 'Primorka',
 'Gambia',
 'Racing Club de France',
 'Grifo III',
 'Grifo IV',
 'Bingo',
 'Damoiselle IV',
 'Crabe II-12',
 'Nina Claire-30',
 'Crabe II-1',
 'Crabe II-4',
 'Nina Claire-2',
 "Qu'Importe",
 'Konstanz',
 'Suzy-2',
 'Mouchette-2',
 'Dansk Idrts Forbund',
 'Marmara',
 'Moseley Wanderers',
 'Chicago Athletic Association-2',
 'Devon and Somerset Wanderers',
 'Unified Team-2',
 'Mistral Hojris',
 'Cook Islands',
 'Mauritius-2',
 'Albania',
 'Romania-1',
 'Pampero',
 'Israel-2',
 'Symphony',
 'Sjhxa',
 'Faneca',
 'Ciocca III',
 'Marinai della nave da guerra "Varese"',
 'Lalage',
 'Gallia II',
 'Dinah V',
 'Czech Republic-2',
 'Nora',
 'Monica',
 'Kullan',
 'Shoveller',
 'Amateur Athletic Association',
 'Circus',
 'Aletta',
 'Widgeon',
 'Inca',
 'Czech Republic-1',
 'Relampago',
 'Foxhunters Hurlingham',
 'Thames Rowing Club',
 'Davenport Turngemeinde, Davenport',
 'Norwegier Turnverein, Brooklyn',
 'Erna Signe',
 'Sirene',
 'Socit Nautique de Bayonne-2',
 'Socit Nautique de Bayonne-1',
 'Anitra',
 'Snude',
 'White Lady',
 'Web II',
 'Web III',
 'Italy-3',
 'Pistoja/Firenze',
 'West Indies Federation',
 'Posillipo III',
 'Tritons Lillois-2',
 'Turnverein Vorwrts, Cleveland',
 'Club Nautique de Franais-1',
 'Monaco-1',
 'Boreas-2',
 'Peri',
 'New York Turnverein, New York',
 'Tichiboo',
 'Siames-Cat',
 'Swaziland',
 'India-1',
 'Italia',
 'Ausonia',
 'Angelita',
 'Burkina Faso',
 'Nortazo',
 'Tom Kyle',
 'Tilly',
 'Esterel-1',
 'North Borneo',
 'Wiking',
 'Buraddoo',
 'Heroine',
 'Burundi',
 'Chok',
 'Atlanta',
 'Germania II',
 'Wannsee',
 'Polyteknisk Roklub-1',
 'Aruba',
 'Buscape II',
 'Nina',
 'Norway-3',
 'Kristiania Roklub-1',
 'Kristiania Roklub',
 'Ormsund Roklub-2',
 'Chuckles',
 'South Africa-2',
 'Chinese Taipei',
 'Winnipeg Shamrocks-1',
 'Olle',
 'United States-10',
 'Camelia',
 'Aschenbrodel',
 'Whitini Star',
 'Puerto Rico-1',
 'Bera',
 'Netherlands-2',
 'Slaghoken',
 'Slaghoken II',
 'Great Britain/Germany',
 'Nikh',
 'Swift',
 'Andorinha',
 'Unified Team-1',
 'Cupidon III',
 'Athens-2',
 'Bulgaria-2',
 'Marga-2',
 'Serendipity',
 "L'Aile VI",
 "Cercle de l'Aviron Roubaix-4",
 'Caprice',
 'New College, Oxford-2',
 'Compigne Polo Club',
 'Vision',
 'Cambridge University Boat Club-2',
 'Trickson VI',
 'St. Rose-2',
 'Calcinhas',
 'Gteborgs Roddfrening-2',
 'Minerva Amsterdam',
 'Chamukina',
 'Nausikaa 4',
 'New York Athletic Club-1',
 'Arcturus',
 'Belgium-1',
 'St. Louis Southwest Turnverein #1-2',
 'Nauru',
 'Jo',
 'Lucky Star',
 'Namoussa',
 'Briar',
 'Panhellenios Gymnastikos Syllogos-1',
 'Netherlands-1',
 'Gabbiano',
 'Gran Gesto',
 'Ceres II',
 'Covunco III',
 'Chicago Archers',
 'Royal Club Nautique de Gand',
 'Roddklubben af 1912-1',
 'Roddklubben af 1912-2',
 'Bucintoro Venezia-1',
 'Bucintoro Venezia',
 'Edelweiss II-1',
 'Bamba',
 'Rush IV',
 'Boston Archers',
 'Ali-Baba IV',
 'Ali-Baba VI',
 'Ali-Baba IX',
 'Upton Park FC',
 'BLO Polo Club, Rugby',
 'Hurlingham-2',
 'Leander Club-1',
 'Indonesia-2',
 'Western Rowing Club-3',
 'Pigoule',
 'South Vietnam',
 'Snowten III',
 'Hungaria',
 'Libellule de Paris',
 'Scram',
 'United States Virgin Islands-2',
 'United States Virgin Islands-1',
 'Amstel Amsterdam',
 'Scotland-3',
 'Peri II',
 'Liverpool Police Team-2',
 'Vinha',
 'Fantasio III',
 'Pousse-Moi Pas VII',
 'Norwegian Rowing Association',
 'LaBandera',
 'Gilliatt V',
 'United States Golf Association-3',
 'Trans-Mississippi Golf Association-2',
 'China-2',
 'China-1',
 'Sarcelle-35',
 'Sarcelle-3',
 'Tango',
 'Argentina-1',
 'Brynhild-2',
 'Espuma del Mar',
 'Twins II',
 'Pupilles de Neptune de Lille #2-1',
 'Beaver',
 'Monaco-2',
 'Baccara',
 'Cobweb-1',
 'Ral-Club Barcelona',
 'Vietnam',
 'Elvis Va',
 'Romolo',
 'Aldebaran II',
 'Aldebaran',
 'Argus',
 'Galatea II',
 'Twins VIII',
 'Antwerpia V',
 'Lotta IV',
 'Saga-2',
 'Mari',
 'Paula',
 'Oranje',
 'Willem-Six',
 'DeRuyter',
 'Acturus',
 'Societ Nautique de la Marne',
 'Mexico-2',
 'Teresita',
 'Barion/Bari-2',
 'Eissero VI',
 'New York Athletic Club-4',
 'K Division Metropolitan Police Team-3',
 'Israel-1',
 'Hong Kong-1',
 'Malaysia-1',
 'Cambodia',
 'Complex II',
 'Allegro',
 'Gam II',
 'Ylliam VIII',
 'Quand-Mme-33',
 'Quand-Mme-2',
 'United States-9',
 'Berliner Ruderclub Sport-Borussia-1',
 'Smyrna',
 'Chinese Taipei-2',
 'Calimucho',
 'Bhutan',
 'North Korea-1',
 'Malaysia-2',
 'Kingfisher',
 'Yangon',
 'Gustel V',
 'Sonja II',
 'Jill',
 'Kiel',
 'KNS',
 'Galt Football Club',
 'Tim-Tam III',
 'Uragan',
 'Kon-Tiki',
 'Babe',
 'Poland-2',
 'Antares',
 'Venilia',
 'Hatuey',
 'Mauritius-1',
 'Cincinnati Archers',
 'Morena',
 'Libellule de Paris-3',
 'Societ Nautique de la Marne-3',
 'Osborne Swimming Club, Manchester',
 'Brussels Swimming and Water Polo Club',
 'Ancora',
 'Saskia',
 'Wales-4',
 'SagaII',
 'Gem',
 'June Climene',
 'Cambria',
 'Oleander XII',
 'Phoenix',
 'Ylliam VII',
 'Ballerina IV',
 'Chicago Athletic Association',
 'Calypse II',
 'Scotland',
 'Scotland-2',
 'Ciocca',
 'Esperia',
 'Tournade-40',
 'Tornade-16',
 'Galejan',
 'Great Britain-4',
 'Cuba-1',
 'Marshall Islands',
 'United States-6',
 'Santa Maria',
 'Dormy-1',
 'Umberta V',
 'Rozenn-3',
 'Jest',
 'Magdalen College Boat Club-1',
 'Western Golf Association-1',
 'Scotia',
 'Red Dragon',
 'R.-V. Germania, Leitmeritz',
 'Hungary-1',
 'Akatonbo',
 'Terrible',
 'Elisabeth V',
 'Studenternes Roklub-2',
 'Rififi',
 'New York Athletic Club #1-1',
 'Partenope',
 'Bermudes',
 'England',
 'Cornwall',
 'Kiribati',
 'United States-7',
 'Diablo',
 'Plume-patte-32',
 'Plume-Patte-5',
 'Pierre et Jean-3',
 'Pierre et Jean-4',
 'Espadarte',
 'Fruits',
 'Belgium-2',
 'Sidi Fekkar-36',
 'Sidi-Fekkar-14',
 'Souvenance',
 'Meteor',
 'Kurush IV',
 'Vesania',
 'Kurush II',
 'Canopus',
 'Crabe I-11',
 'Crabe I-3',
 'Crabe I-2',
 'Gwendoline-22',
 'Gwendoline-2',
 'United States/France',
 'Vicking',
 'Daisy',
 'Virginie',
 'Acipactli',
 'Belgium-4',
 'Pegaso',
 'Girl Pat',
 'Fada',
 'Bu III',
 'Lerina',
 'Bagatelle Polo Club, Paris',
 'Bem II',
 'St. Margrite',
 'Hollandia',
 'Aphrodite',
 'Bonzo',
 'Socit Nautique de la Basse Seine-1',
 'Socit Nautique de la Basse Seine-2',
 'Univ. of Brussels',
 'Concordia Turnverein, St Louis',
 'Rowing Club Castillon-3',
 'Frip IV',
 'Mad Dog',
 'Hb-24',
 'Hb-20',
 'South St Louis Turnverein, St Louis',
 'Century Boat Club-1',
 'Unique',
 'Pan-Hellenic Athletic Club',
 'Phalainis ton Thorichtou "Hydra"-2',
 'Viking',
 'Silja',
 'Bermudian',
 'Dresden',
 'United States/Great Britain',
 'Mignon-29',
 'Mignon-3',
 'Favorite-17',
 'Favorite-1',
 'St. Louis Amateur Athletic Association',
 'Naiad',
 'Pakaria',
 'Ireland-3',
 'Serbia-2',
 'United States-14',
 'Oxalis',
 'Gitana-21',
 'Gitana-2',
 'Joy',
 'Thalatta',
 'Trintel II',
 'Central Turnverein, Chicago',
 'Galopin-20',
 'Galopin-9',
 'France-4',
 'Berliner Ruderclub',
 'Rhythm',
 'Turnverein Vorwrts, Chicago',
 'Guanahani',
 'Unknown',
 'Spirit III',
 'Pannonia RC/National RC',
 'Bella',
 'May-Be 1960',
 'May Be',
 'Inga-Lill XXXXIII',
 'Mexico-1',
 'Nirwana',
 'Omilos Ereton Peiraios-2',
 'Llanoria',
 'Marmi II-1',
 'Kitty-1',
 'Vaxholm Roddklubb',
 'Tuvalu',
 'A North American Team',
 'Nirefs',
 'Proteus II',
 'Finn II',
 'Impala',
 'Missouri Athletic Club-3',
 'Pam',
 'Oleander II',
 'Apache',
 'Roklubb Kbnhavn-2',
 'Tu-Fri',
 'Tutti V',
 'Cha-Cha III',
 'Augsburg',
 'Leander Club #2-2',
 'Ariel',
 'Encore',
 'Feo',
 'Seawanhaka Boat Club-1',
 'Gem II',
 'Gem III',
 'Gem IV',
 'Gem VII',
 'Pupilles de Neptune de Lille #1-3',
 'Chaje II',
 'Ludwigshafener Ruder Verein-1',
 'Leander Club #1-1',
 'Dylan-2',
 'Moorina',
 '30. Februar',
 'Cercle Nautique de Reims-4',
 'Cuba-2',
 'Struten',
 'Gyrinus-1',
 'Ylliam II',
 'East Germany-3',
 'Paka V',
 'Brigantia',
 'Sydney Rowing Club',
 'Espardate',
 'Australia/Great Britain',
 'Kannibaltje',
 'Milwaukee Athletic Club-1',
 'Xantippa',
 'Skum',
 'Miss Denmark 1964',
 'Kemphaan',
 'Helsingfors R. K.',
 'Newfoundland',
 'Emily',
 'Fram III',
 'Mizar',
 'Ubu',
 'St. Louis Southwest Turnverein #2-3',
 'Socialer Turnverein, Detroit',
 'Bohemia-1',
 'Essen',
 'Miss Nippon V',
 'Argeste',
 'Gullvinge',
 'United States-4',
 'South Korea-1',
 'Bajazzo',
 'Cinara-13',
 'Ilderim',
 'Tantalus',
 'Peiraikos Syndesmos-2',
 'Baby-9',
 'Baby-1',
 'Femur-18',
 'Femur-1',
 'Kosovo',
 'Colette-10',
 'Colette-12',
 'Germany/United States',
 'Germania Ruder Club, Hamburg',
 'Freddy',
 'Rika II',
 'Korshun',
 'Hungary-2',
 'Patricia',
 'Tlaloc',
 'Springbok',
 'Aretusa',
 'Quicksilver-2',
 'Viktoriya',
 'Germania Ruder Club, Hamburg-2',
 'Omilos Ereton Smyrnis',
 'Belarus-2',
 'Alcaid',
 'Finland-1',
 'Finland-2',
 'Alain IV',
 'Jupiter',
 'Three Leaves',
 'Philadelphia Turngemeinde, Philadelphia',
 'K.S.S.S. 1912-2',
 'Unified Team-3',
 'Paka',
 'Sheerio',
 'Pan II',
 'Pasodoble',
 'Freja',
 'India-2',
 'Sass-2',
 'Roy',
 'Ukraine-1',
 'Deutscher Schwimm Verband Berlin',
 'Jet',
 'Belgium-3',
 'Shrew II',
 'Sylvia',
 'Salamander',
 'Denmark-3',
 'Ingegerd',
 'Slovakia-2',
 'Johan',
 'Jamaica-2',
 'Andromeda',
 'Hornet',
 'South Sudan',
 'Sweden-4',
 'Chance',
 'Brat',
 'Yeoman V',
 'Knigsberg',
 'Don Schufro',
 'Vinga-1',
 'Aloha II',
 'Raili',
 'Syndi',
 'Vento Sul',
 'Sans Atout-1',
 'Miss Nippon IV',
 'New Zealand-1',
 'Tramontane',
 'Sandra',
 'Milwaukee Turnverein, Milwaukee',
 'Nurdug II',
 'Eleda',
 'Lbeck',
 'Yeoman',
 'Boer Team',
 'Beatrijs III-1',
 'Lancet',
 'West Germany-3',
 'Lesotho',
 'Ravenswood Boat Club-2',
 'Whisper',
 'Irene',
 'Balaton',
 'Kuling',
 'Sif',
 'Djinn',
 'Mascotte',
 'Bona Fide',
 'Laurea-1',
 'Skidoo',
 'Tomahawk II',
 'Whirlaway',
 'Sorais-2',
 'Minotaur',
 'United States-5',
 'Surprise',
 'Zut',
 'Tan-Fe-Pah',
 'Ciss',
 'Australia-3',
 'Bohemia-3',
 'Boreas',
 'MitaII',
 'Escapade',
 'Slovakia-1',
 'Ralia',
 'Clearwater',
 'Angerburg',
 'Singapore-2',
 'United States-8',
 'Barco Deloro',
 'Dick-8',
 'Yugoslavia-2',
 'Kalayaan',
 'Bohemia-2',
 'Olimpia',
 'Macky VI',
 'Nrnberg',
 'Nephos I',
 'Tengiri',
 'Hayama',
 'Rush VII',
 'Rush V',
 'Ethnikos Gymnastikos Syllogos',
 'John B',
 'Bim',
 'Bonaparte',
 'North Korea-2',
 'Mythilus',
 'Rambo',
 'Floresco',
 'Hong Kong-2',
 'Luxembourg-2',
 'Lucky',
 'Spirit VI',
 'Lully II',
 'Sildra-1',
 'Noreg',
 'Subbnboana',
 'Phalainis ton Thorichtou "Psara"-3',
 'Slovenia-1',
 'Rostock',
 'Norman-1',
 'Olympion',
 ...]

- Afficher une liste de colonnes :

In [41]:
liste = ["Sex","Age"]
df[["Sex","Age"]]

       Sex   Age
0        M  24.0
1        M  23.0
2        M  24.0
3        M  34.0
4        F  21.0
...     ..   ...
271111   M  29.0
271112   M  27.0
271113   M  27.0
271114   M  30.0
271115   M  34.0

[271116 rows x 2 columns]

#### - Manipuler les lignes

- Afficher la 15 ème ligne

In [42]:
df.iloc[15]

ID                                             6.0
Name                               Per Knut Aaland
Sex                                              M
Age                                           33.0
Height                                       188.0
Weight                                        75.0
Team                                 United States
NOC                                            USA
Games                                  1994 Winter
Year                                          1994
Season                                      Winter
City                                   Lillehammer
Sport                         Cross Country Skiing
Event     Cross Country Skiing Men's 30 kilometres
Medal                                          NaN
Name: 15, dtype: object

- Affichez la 15 ème ligne jusqu'à la 20 ème

In [12]:
df.iloc[15:20]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
15,6.0,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 30 kilometres,NaN
16,6.0,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN
17,6.0,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
18,7.0,John Aalberg,M,31.0,183.0,72.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
19,7.0,John Aalberg,M,31.0,183.0,72.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,NaN

- Affichez les 5 dernières lignes

In [44]:
df.iloc[-5:]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
271111,135569.0,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
271112,135570.0,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
271113,135570.0,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
271114,135571.0,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
271115,135571.0,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

#### Les manipulations à connaitre

- Selectionner les lignes respectant une condition

In [14]:
df[df["Age"] > 90]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
98118,49663.0,Winslow Homer,M,96.0,NaN,NaN,United States,USA,1932 Summer,1932,Summer,Los Angeles,Art Competitions,"Art Competitions Mixed Painting, Unknown Event",NaN
257054,128719.0,John Quincy Adams Ward,M,97.0,NaN,NaN,United States,USA,1928 Summer,1928,Summer,Amsterdam,Art Competitions,"Art Competitions Mixed Sculpturing, Statues",NaN

- respectant plusieurs conditions

In [15]:
df[(df["Age"] > 90) & (df["Year"]<1930)]  # et = &, ou = |

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
257054,128719.0,John Quincy Adams Ward,M,97.0,NaN,NaN,United States,USA,1928 Summer,1928,Summer,Amsterdam,Art Competitions,"Art Competitions Mixed Sculpturing, Statues",NaN

- Compter le nombre d'occurences de chacunes des valeurs possibles d'une colonne

In [45]:
df.Medal.value_counts()

Medal
Gold      13372
Bronze    13295
Silver    13116
Name: count, dtype: int64

- Remplacer les valeurs manquantes (egales "Nan") par une autre valeur

In [47]:
df.Medal = df.Medal.fillna(value=0)

- Autre solution : supprimer les lignes avec des valeurs manquantes

In [18]:
df = df.dropna(subset=['Medal'])

- Affichez la valeur la plus fréquente d'une colonne (par exemple le sportif le plus présent du jeu de donnée)

In [48]:
best_sportif = df.Name.mode()
print(best_sportif[0])

Robert Tait McKenzie

- Affichez valeurs d'une colonne pour les lignes respectant une condition sur une autre colonne. Exemple : les sports du meilleur sportif.

In [49]:
df['Sport'][df['Name']==best_sportif[0]]

154798    Art Competitions
154799    Art Competitions
154800    Art Competitions
154801    Art Competitions
154802    Art Competitions
154803    Art Competitions
154804    Art Competitions
154805    Art Competitions
154806    Art Competitions
154807    Art Competitions
154808    Art Competitions
154809    Art Competitions
154810    Art Competitions
154811    Art Competitions
154812    Art Competitions
154813    Art Competitions
154814    Art Competitions
154815    Art Competitions
154816    Art Competitions
154817    Art Competitions
154818    Art Competitions
154819    Art Competitions
154820    Art Competitions
154821    Art Competitions
154822    Art Competitions
154823    Art Competitions
154824    Art Competitions
154825    Art Competitions
154826    Art Competitions
154827    Art Competitions
154828    Art Competitions
154829    Art Competitions
154830    Art Competitions
154831    Art Competitions
154832    Art Competitions
154833    Art Competitions
154834    Art Competitions
154835    Art Competitions
154836    Art Competitions
154837    Art Competitions
154838    Art Competitions
154839    Art Competitions
154840    Art Competitions
154841    Art Competitions
154842    Art Competitions
154843    Art Competitions
154844    Art Competitions
154845    Art Competitions
154846    Art Competitions
154847    Art Competitions
154848    Art Competitions
154849    Art Competitions
154850    Art Competitions
154851    Art Competitions
154852    Art Competitions
154853    Art Competitions
154854    Art Competitions
154855    Art Competitions
Name: Sport, dtype: object

- le min et max d'une colonne

In [50]:
df['Age'].max()

97.0

- La ligne du sportif le plus petit

In [51]:
line_smallest = df['Height'].idxmin()
df.loc[line_smallest]

ID                                         15150.0
Name                               Rosario Briones
Sex                                              F
Age                                           15.0
Height                                       127.0
Weight                                        42.0
Team                                        Mexico
NOC                                            MEX
Games                                  1968 Summer
Year                                          1968
Season                                      Summer
City                                   Mexico City
Sport                                   Gymnastics
Event     Gymnastics Women's Individual All-Around
Medal                                            0
Name: 29333, dtype: object

- La moyenne, medianne, ...

In [23]:
df.Age.mean()

25.556898357297374

- Grouper sur une colonne, et appliquer un indicateur sur chaque groupe. Ex: l'age min et max par sport

In [52]:
group = df.groupby('Sport')
print(group)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x000001F45DA2A7F0>

In [53]:
df_agg = group.Age.agg(['min', 'max'])
df_agg

                   min   max
Sport
Aeronautics       26.0  26.0
Alpine Skiing     14.0  55.0
Alpinism          22.0  57.0
Archery           14.0  71.0
Art Competitions  14.0  97.0
...                ...   ...
Tug-Of-War        17.0  45.0
Volleyball        15.0  41.0
Water Polo        14.0  45.0
Weightlifting     15.0  45.0
Wrestling         15.0  50.0

[66 rows x 2 columns]

- Faire des opérations entre colonnes. Exemple : soustraire une colonne à une autre

In [26]:
df_agg["diff"] = df_agg["max"] - df_agg["min"]
df_agg

                   min   max  diff
Sport
Aeronautics       26.0  26.0   0.0
Alpine Skiing     14.0  55.0  41.0
Alpinism          22.0  57.0  35.0
Archery           14.0  71.0  57.0
Art Competitions  14.0  97.0  83.0
...                ...   ...   ...
Tug-Of-War        17.0  45.0  28.0
Volleyball        15.0  41.0  26.0
Water Polo        14.0  45.0  31.0
Weightlifting     15.0  45.0  30.0
Wrestling         15.0  50.0  35.0

[66 rows x 3 columns]

### Fusionner plusieurs dataframe

In [27]:
# import csv 
df_continent = pd.read_csv("pays_continents.csv", encoding = "ISO-8859-1",  sep=";" )

Merge permet de fusionner les deux dataframes en fournissant le nom de la colonne suivant laquelle faire la fusion

In [28]:
df_merge = df.merge(df_continent, left_on="City", right_on="Ville", how='left')
df_merge

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,Ville,Continent
0,1.0,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,Manquant,NaN,NaN
1,2.0,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,Manquant,NaN,NaN
2,3.0,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,Manquant,NaN,NaN
3,4.0,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Paris,Europe
4,4.0,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold,Paris,Europe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350069,135569.0,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,Manquant,Innsbruck,Europe
350070,135570.0,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",Manquant,NaN,NaN
350071,135570.0,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",Manquant,NaN,NaN
350072,135571.0,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,Manquant,Nagano,Asie
350073,135571.0,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,Manquant,Salt Lake City,Amérique du Nord

- la méthode concat permet d'ajouter les lignes d'un dataframe à un autre